package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// generatedTemplate is the minimal compose file VAC synthesises for repos
// that ship only a Dockerfile. It mirrors mvp.md § Deployment Model exactly.
const generatedTemplate = `# Auto-generated by VAC for a Dockerfile-only repo.
# Do not edit — regenerated on every deploy.
services:
  app:
    build: .
    restart: always
    env_file:
      - .env
`

// dockerfileTemplate wraps a repo whose Dockerfile lives at a non-default path.
// `build: .` (in generatedTemplate) implies ./Dockerfile, so this is only used
// when the path differs.
const dockerfileTemplate = `# Auto-generated by VAC for a single-Dockerfile repo.
# Do not edit — regenerated on every deploy.
services:
  app:
    build:
      context: .
      dockerfile: %q
    restart: always
    env_file:
      - .env
`

// Wrap writes the generated compose file to destPath, ensuring the parent
// directory exists. Returns the absolute path so the caller can update the
// Result struct from Detect.
func Wrap(destPath string) (string, error) {
	return writeWrap(destPath, generatedTemplate)
}

// WrapDockerfile is Wrap for a Dockerfile at an explicit, non-default path. A
// default/empty path delegates to Wrap (whose `build: .` already means
// ./Dockerfile). The path must be repo-relative — callers validate that first.
func WrapDockerfile(destPath, dockerfilePath string) (string, error) {
	dockerfilePath = strings.TrimSpace(dockerfilePath)
	if dockerfilePath == "" || dockerfilePath == "Dockerfile" {
		return Wrap(destPath)
	}
	return writeWrap(destPath, fmt.Sprintf(dockerfileTemplate, dockerfilePath))
}

// resourceOverrideName is the compose override VAC writes to enforce a per-app
// RAM limit (plan 06). It's a second `-f` file merged over the user's compose at
// `docker compose up`, so the user's own file is never rewritten.
const resourceOverrideName = "vac-resources.override.yml"

// WriteResourceOverride writes a compose override next to composeFile that caps
// every service at memLimitMB mebibytes via `mem_limit`, and returns its path.
// A non-positive limit (or a compose with no services) writes nothing and
// returns "". The limit is per-container: it guarantees no single container can
// exceed the cap, which is the OOM-protection goal — on a small box one runaway
// container is what takes the host down.
func WriteResourceOverride(composeFile string, memLimitMB int) (string, error) {
	if memLimitMB <= 0 {
		return "", nil
	}
	services, err := Parse(composeFile)
	if err != nil {
		return "", err
	}
	if len(services) == 0 {
		return "", nil
	}
	var b strings.Builder
	b.WriteString("# Auto-generated by VAC — per-app memory limit (plan 06).\n")
	b.WriteString("# Do not edit — regenerated on every deploy. Merged over your\n")
	b.WriteString("# compose at `docker compose up`; caps each container so one\n")
	b.WriteString("# can't OOM the box.\n")
	b.WriteString("services:\n")
	for _, s := range services {
		fmt.Fprintf(&b, "  %s:\n    mem_limit: %dm\n", s.Name, memLimitMB)
	}
	dest := filepath.Join(filepath.Dir(composeFile), resourceOverrideName)
	if err := os.WriteFile(dest, []byte(b.String()), 0o644); err != nil { //nolint:gosec // override is non-secret, world-readable like the compose file
		return "", fmt.Errorf("compose: write override: %w", err)
	}
	return dest, nil
}

func writeWrap(destPath, body string) (string, error) {
	abs, err := filepath.Abs(destPath)
	if err != nil {
		return "", fmt.Errorf("compose: abs: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil { //nolint:gosec // G301: app working dir, traversed by the vac-api owner and the docker daemon
		return "", fmt.Errorf("compose: mkdir: %w", err)
	}
	if err := os.WriteFile(abs, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("compose: write: %w", err)
	}
	return abs, nil
}
