package compose

import (
	"fmt"
	"os"
	"path/filepath"
)

// generatedTemplate is the minimal compose file VAC synthesises for repos
// that ship only a Dockerfile. It mirrors mvp.md § Deployment Model exactly.
const generatedTemplate = `# Auto-generated by VAC for a Dockerfile-only repo.
# Do not edit — regenerated on every deploy.
services:
  app:
    build: .
    restart: always
    env_file:
      - .env
`

// Wrap writes the generated compose file to destPath, ensuring the parent
// directory exists. Returns the absolute path so the caller can update the
// Result struct from Detect.
func Wrap(destPath string) (string, error) {
	abs, err := filepath.Abs(destPath)
	if err != nil {
		return "", fmt.Errorf("compose: abs: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return "", fmt.Errorf("compose: mkdir: %w", err)
	}
	if err := os.WriteFile(abs, []byte(generatedTemplate), 0o644); err != nil {
		return "", fmt.Errorf("compose: write: %w", err)
	}
	return abs, nil
}
