package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// generatedTemplate is the minimal compose file VAC synthesises for repos
// that ship only a Dockerfile. It mirrors mvp.md § Deployment Model exactly.
const generatedTemplate = `# Auto-generated by VAC for a Dockerfile-only repo.
# Do not edit — regenerated on every deploy.
services:
  app:
    build: .
    restart: always
    env_file:
      - .env
`

// dockerfileTemplate wraps a repo whose Dockerfile lives at a non-default path.
// `build: .` (in generatedTemplate) implies ./Dockerfile, so this is only used
// when the path differs.
const dockerfileTemplate = `# Auto-generated by VAC for a single-Dockerfile repo.
# Do not edit — regenerated on every deploy.
services:
  app:
    build:
      context: .
      dockerfile: %q
    restart: always
    env_file:
      - .env
`

// Wrap writes the generated compose file to destPath, ensuring the parent
// directory exists. Returns the absolute path so the caller can update the
// Result struct from Detect.
func Wrap(destPath string) (string, error) {
	return writeWrap(destPath, generatedTemplate)
}

// WrapDockerfile is Wrap for a Dockerfile at an explicit, non-default path. A
// default/empty path delegates to Wrap (whose `build: .` already means
// ./Dockerfile). The path must be repo-relative — callers validate that first.
func WrapDockerfile(destPath, dockerfilePath string) (string, error) {
	dockerfilePath = strings.TrimSpace(dockerfilePath)
	if dockerfilePath == "" || dockerfilePath == "Dockerfile" {
		return Wrap(destPath)
	}
	return writeWrap(destPath, fmt.Sprintf(dockerfileTemplate, dockerfilePath))
}

func writeWrap(destPath, body string) (string, error) {
	abs, err := filepath.Abs(destPath)
	if err != nil {
		return "", fmt.Errorf("compose: abs: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return "", fmt.Errorf("compose: mkdir: %w", err)
	}
	if err := os.WriteFile(abs, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("compose: write: %w", err)
	}
	return abs, nil
}
