package adapter

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// frameworkAdapter synthesizes a Dockerfile + compose from a per-framework
// template. Today only React is supported (build → static output served by
// nginx); the switch is structured so more frameworks slot in later.
type frameworkAdapter struct{}

func (frameworkAdapter) Kind() string { return KindFramework }

// reactDockerfileTemplate: %s build command, %s output dir.
const reactDockerfileTemplate = `# Auto-generated by VAC (framework: react).
# Do not edit — regenerated on every deploy.
FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN %s
FROM nginx:alpine
COPY --from=build /app/%s /usr/share/nginx/html
`

// frameworkComposeTemplate: %q generated Dockerfile path.
const frameworkComposeTemplate = `# Auto-generated by VAC (framework build).
# Do not edit — regenerated on every deploy.
services:
  app:
    build:
      context: .
      dockerfile: %q
    restart: always
    ports:
      - "80"
    env_file:
      - .env
`

const frameworkDockerfileName = "Dockerfile.vac"

func (frameworkAdapter) Prepare(_ context.Context, repoDir string, cfg BuildConfig) (string, error) {
	switch strings.ToLower(strings.TrimSpace(cfg.Framework)) {
	case "react":
		return prepareReact(repoDir, cfg)
	default:
		return "", fmt.Errorf("adapter: unsupported framework %q (only react today)", cfg.Framework)
	}
}

func prepareReact(repoDir string, cfg BuildConfig) (string, error) {
	build := strings.TrimSpace(cfg.BuildCommand)
	if build == "" {
		build = "npm install && npm run build"
	}
	// Vite outputs to dist/ by default; CRA to build/. Default to dist and let
	// the operator override via the build command / future config.
	outDir := "dist"

	dfPath := filepath.Join(repoDir, frameworkDockerfileName)
	dockerfile := fmt.Sprintf(reactDockerfileTemplate, build, outDir)
	if err := os.WriteFile(dfPath, []byte(dockerfile), 0o644); err != nil {
		return "", fmt.Errorf("adapter: write Dockerfile: %w", err)
	}

	body := fmt.Sprintf(frameworkComposeTemplate, frameworkDockerfileName)
	dest := composeWrapPath(repoDir)
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("adapter: write compose: %w", err)
	}
	return dest, nil
}

// detectFramework inspects package.json for a known framework dependency.
// Returns the framework key (e.g. "react") or "" when none is recognized.
func detectFramework(repoDir string) string {
	raw, err := os.ReadFile(filepath.Join(repoDir, "package.json"))
	if err != nil {
		return ""
	}
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
	}
	if json.Unmarshal(raw, &pkg) != nil {
		return ""
	}
	if _, ok := pkg.Dependencies["react"]; ok {
		return "react"
	}
	if _, ok := pkg.DevDependencies["react"]; ok {
		return "react"
	}
	return ""
}
