package adapter

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// preparePython builds a Python web app (Django/Flask/FastAPI or a bare script)
// into a slim multi-stage image: deps compile in a builder venv, the runtime
// stage carries only the venv. The start command is resolved from the repo
// (overridable via build_config or a Procfile `web:` line).
func preparePython(repoDir string, cfg BuildConfig) (string, error) {
	port := cfg.Port
	if port == 0 {
		port = 8000
	}
	cmdLine, serverPkg := pythonStart(repoDir, cfg, port)

	serverInstall := ""
	if serverPkg != "" {
		// Ensure the WSGI/ASGI server exists even when it isn't pinned in the
		// project's requirements (a common omission in example repos).
		serverInstall = fmt.Sprintf("\nRUN pip install --no-cache-dir %s", serverPkg)
	}

	df := fmt.Sprintf(`# Auto-generated by VAC (framework: python).
# Do not edit — regenerated on every deploy.
FROM python:3.12-slim AS builder
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /app
COPY . .
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; \
    elif [ -f pyproject.toml ]; then pip install --no-cache-dir .; \
    fi%s
FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PATH="/opt/venv/bin:$PATH"
WORKDIR /app
COPY --from=builder /opt/venv /opt/venv
COPY . .
ENV PORT=%d
EXPOSE %d
%s
`, serverInstall, port, port, cmdLine)
	return writeFramework(repoDir, df, port)
}

// pythonStart resolves (CMD line, server package to install). Priority:
// explicit config command → Procfile `web:` line → Django (manage.py + wsgi) →
// FastAPI → Flask → a bare `python <entry>`. The CMD is exec-form for resolved
// commands and shell-form for operator-supplied ones (which may contain pipes).
func pythonStart(repoDir string, cfg BuildConfig, port int) (cmd, serverPkg string) {
	if c := strings.TrimSpace(cfg.StartCommand); c != "" {
		return "CMD " + c, ""
	}
	if web := procfileWeb(repoDir); web != "" {
		return "CMD " + web, ""
	}
	// Django: manage.py at root + a sibling package holding wsgi.py.
	if fileExists(filepath.Join(repoDir, "manage.py")) {
		if mod := findPythonModule(repoDir, "wsgi.py"); mod != "" {
			bind := fmt.Sprintf("0.0.0.0:%d", port)
			return "CMD " + execCmd([]string{"gunicorn", "--bind", bind, mod + ":application"}), "gunicorn"
		}
	}
	// FastAPI: an ASGI app — serve with uvicorn.
	if mod := findPythonAppModule(repoDir, "FastAPI("); mod != "" {
		return "CMD " + execCmd([]string{"uvicorn", mod + ":app", "--host", "0.0.0.0", "--port", fmt.Sprintf("%d", port)}), "uvicorn[standard]"
	}
	// Flask: a WSGI app — serve with gunicorn.
	if mod := findPythonAppModule(repoDir, "Flask("); mod != "" {
		bind := fmt.Sprintf("0.0.0.0:%d", port)
		return "CMD " + execCmd([]string{"gunicorn", "--bind", bind, mod + ":app"}), "gunicorn"
	}
	// Bare script.
	for _, entry := range []string{"main.py", "app.py", "server.py"} {
		if fileExists(filepath.Join(repoDir, entry)) {
			return "CMD " + execCmd([]string{"python", entry}), ""
		}
	}
	return "CMD " + execCmd([]string{"python", "main.py"}), ""
}

// procfileWeb returns the command from a Procfile `web:` line, or "".
func procfileWeb(repoDir string) string {
	b, err := os.ReadFile(filepath.Join(repoDir, "Procfile")) //nolint:gosec // G304: operator's cloned build input
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(b), "\n") {
		if rest, ok := strings.CutPrefix(strings.TrimSpace(line), "web:"); ok {
			return strings.TrimSpace(rest)
		}
	}
	return ""
}

// findPythonModule locates a file named `name` within two directory levels and
// returns the dotted module path of its package (e.g. myproj/wsgi.py →
// "myproj.wsgi"). Empty when not found.
func findPythonModule(repoDir, name string) string {
	var found string
	_ = filepath.WalkDir(repoDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || found != "" {
			return nil
		}
		rel, _ := filepath.Rel(repoDir, path)
		if d.IsDir() {
			if rel != "." && (strings.HasPrefix(filepath.Base(path), ".") || strings.Count(rel, string(filepath.Separator)) >= 2) {
				return fs.SkipDir
			}
			return nil
		}
		if d.Name() == name {
			found = strings.TrimSuffix(filepath.ToSlash(rel), ".py")
			found = strings.ReplaceAll(found, "/", ".")
		}
		return nil
	})
	return found
}

// findPythonAppModule finds the first .py file (within two levels) whose source
// contains marker (e.g. "FastAPI(") and returns its dotted module path.
func findPythonAppModule(repoDir, marker string) string {
	var found string
	_ = filepath.WalkDir(repoDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || found != "" {
			return nil
		}
		rel, _ := filepath.Rel(repoDir, path)
		if d.IsDir() {
			if rel != "." && (strings.HasPrefix(filepath.Base(path), ".") || strings.Count(rel, string(filepath.Separator)) >= 2) {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(d.Name(), ".py") {
			return nil
		}
		b, rerr := os.ReadFile(path) //nolint:gosec // G304: operator's cloned build input
		if rerr == nil && strings.Contains(string(b), marker) {
			found = strings.TrimSuffix(filepath.ToSlash(rel), ".py")
			found = strings.ReplaceAll(found, "/", ".")
		}
		return nil
	})
	return found
}
