package adapter

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// frameworkAdapter synthesizes a Dockerfile + compose from a per-framework
// template. Each framework lowers to the same shape the rest of the pipeline
// expects: a generated Dockerfile.vac plus a compose.yaml that builds it and
// exposes one routable port. New frameworks slot into the Prepare switch and
// detectFramework below.
type frameworkAdapter struct{}

func (frameworkAdapter) Kind() string { return KindFramework }

// Framework keys. These are the values stored in build_config.framework and the
// ids the UI's framework picker sends.
const (
	FrameworkReact  = "react"
	FrameworkVite   = "vite"
	FrameworkNext   = "nextjs"
	FrameworkAstro  = "astro"
	FrameworkNode   = "node"
	FrameworkPython = "python"
)

const frameworkDockerfileName = "Dockerfile.vac"

// frameworkComposeTemplate builds the generated Dockerfile and exposes a single
// container port for Caddy to route to. %q is the generated Dockerfile path,
// %q the exposed port (string so it serialises cleanly into the YAML list).
const frameworkComposeTemplate = `# Auto-generated by VAC (framework build).
# Do not edit — regenerated on every deploy.
services:
  app:
    build:
      context: .
      dockerfile: %q
    restart: always
    expose:
      - %q
    env_file:
      - .env
`

func (frameworkAdapter) Prepare(_ context.Context, repoDir string, cfg BuildConfig) (string, error) {
	fw := strings.ToLower(strings.TrimSpace(cfg.Framework))
	// In auto mode the stored config carries no framework; recover it from the
	// cloned repo so `build_kind:"framework"` and `build_kind:"auto"` converge.
	if fw == "" {
		fw = detectFramework(repoDir)
	}
	switch fw {
	case FrameworkReact:
		return prepareStaticNode(repoDir, cfg, FrameworkReact, "dist", spaNginxConf())
	case FrameworkVite:
		return prepareStaticNode(repoDir, cfg, FrameworkVite, "dist", spaNginxConf())
	case FrameworkNext:
		return prepareNext(repoDir, cfg)
	case FrameworkAstro:
		return prepareAstro(repoDir, cfg)
	case FrameworkNode:
		return prepareNode(repoDir, cfg)
	case FrameworkPython:
		return preparePython(repoDir, cfg)
	default:
		return "", fmt.Errorf("adapter: unsupported framework %q (supported: react, vite, nextjs, astro, node, python)", cfg.Framework)
	}
}

// writeFramework writes the generated Dockerfile and compose wrapper, returning
// the compose path. Every per-framework prepare funnels through here so the
// compose shape (build context, exposed port, env_file) stays identical.
func writeFramework(repoDir, dockerfile string, port int) (string, error) {
	dfPath := filepath.Join(repoDir, frameworkDockerfileName)
	// 0644: a generated build manifest, not a secret — the docker build reads it.
	if err := os.WriteFile(dfPath, []byte(dockerfile), 0o644); err != nil {
		return "", fmt.Errorf("adapter: write Dockerfile: %w", err)
	}
	body := fmt.Sprintf(frameworkComposeTemplate, frameworkDockerfileName, fmt.Sprintf("%d", port))
	dest := composeWrapPath(repoDir)
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("adapter: write compose: %w", err)
	}
	return dest, nil
}

// DetectFramework returns the framework key (e.g. "nextjs") detected in a
// cloned repo, or "" when none is recognised. Exposed for the new-app wizard's
// repo probe, which surfaces the detected framework before a deploy.
func DetectFramework(repoDir string) string { return detectFramework(repoDir) }

// detectFramework inspects the repo for a known framework, returning its key
// (e.g. "nextjs") or "" when none is recognised. Order is most-specific first:
// the Node meta-frameworks (Next, Astro) win over the generic Vite/React/Node
// fallbacks, and a Node app wins over Python when both manifests are present
// (a polyglot repo's package.json is the likelier entrypoint here).
func detectFramework(repoDir string) string {
	if pkg, ok := readPackageJSON(repoDir); ok {
		switch {
		case pkg.hasDep("next"):
			return FrameworkNext
		case pkg.hasDep("astro"):
			return FrameworkAstro
		case pkg.hasDep("vite"):
			return FrameworkVite
		case pkg.hasDep("react"):
			return FrameworkReact
		default:
			return FrameworkNode
		}
	}
	if hasAnyFile(repoDir, "requirements.txt", "pyproject.toml", "Pipfile", "manage.py") {
		return FrameworkPython
	}
	return ""
}

// packageJSON is the slice of package.json the adapter cares about.
type packageJSON struct {
	Dependencies    map[string]string `json:"dependencies"`
	DevDependencies map[string]string `json:"devDependencies"`
	Scripts         map[string]string `json:"scripts"`
	Main            string            `json:"main"`
}

func (p packageJSON) hasDep(name string) bool {
	if _, ok := p.Dependencies[name]; ok {
		return true
	}
	_, ok := p.DevDependencies[name]
	return ok
}

func readPackageJSON(repoDir string) (packageJSON, bool) {
	raw, err := os.ReadFile(filepath.Join(repoDir, "package.json")) //nolint:gosec // G304: repoDir is the operator's cloned build input by design
	if err != nil {
		return packageJSON{}, false
	}
	var pkg packageJSON
	if json.Unmarshal(raw, &pkg) != nil {
		return packageJSON{}, false
	}
	return pkg, true
}

func hasAnyFile(repoDir string, names ...string) bool {
	for _, n := range names {
		if fileExists(filepath.Join(repoDir, n)) {
			return true
		}
	}
	return false
}
