package adapter

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const frameworkNginxConfName = "vac-nginx.conf"

// nodeInstall is a lockfile-aware dependency install, run inside the image so
// the host's package manager / arch never leaks in. Mirrors what Vercel's and
// Docker's official examples do: pick the manager from the committed lockfile.
const nodeInstall = `RUN if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \
    elif [ -f yarn.lock ]; then corepack enable && yarn install --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    else npm install; fi`

// nodeBuild runs the project's build script through the detected package
// manager. Used by the server frameworks; the static path takes a single
// user-overridable build command instead.
const nodeBuild = `RUN if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm run build; \
    elif [ -f yarn.lock ]; then corepack enable && yarn build; \
    else npm run build; fi`

// prepareStaticNode builds a Node project and serves its static output dir via
// nginx — the React/Vite (and Astro-static) shape. A single-stage build keeps
// the generated file small; the build command stays user-overridable.
func prepareStaticNode(repoDir string, cfg BuildConfig, framework, defaultOut, nginxConf string) (string, error) {
	// Default to the lockfile-aware install+build the other Node paths use, so a
	// pnpm/yarn project is built with its own package manager (and lockfile)
	// rather than a blanket `npm install` — npm re-resolves from scratch and
	// fails hard on peer conflicts a pnpm/yarn lockfile already pinned past.
	// An explicit build command overrides the whole step.
	steps := nodeInstall + "\n" + nodeBuild
	if c := strings.TrimSpace(cfg.BuildCommand); c != "" {
		steps = "RUN " + c
	}
	out := strings.TrimSpace(cfg.StaticDir)
	if out == "" {
		out = defaultOut
	}
	if err := writeNginxConf(repoDir, nginxConf); err != nil {
		return "", err
	}
	df := fmt.Sprintf(`# Auto-generated by VAC (framework: %s).
# Do not edit — regenerated on every deploy.
FROM node:22-alpine AS build
WORKDIR /app
COPY . .
%s
FROM nginx:alpine
COPY --from=build /app/%s /usr/share/nginx/html
COPY %s /etc/nginx/conf.d/default.conf
`, framework, steps, out, frameworkNginxConfName)
	return writeFramework(repoDir, df, 80)
}

// prepareNext branches on the Next.js output mode declared in next.config.*:
// standalone → a minimal `node server.js` image; export → static `out/` via
// nginx; default → a full `next start` server. All listen on 3000 (HOSTNAME
// 0.0.0.0 so the container is reachable behind Caddy).
func prepareNext(repoDir string, cfg BuildConfig) (string, error) {
	switch detectNextMode(repoDir) {
	case "export":
		if err := writeNginxConf(repoDir, mpaNginxConf()); err != nil {
			return "", err
		}
		df := fmt.Sprintf(`# Auto-generated by VAC (framework: nextjs, mode: export).
# Do not edit — regenerated on every deploy.
FROM node:22-alpine AS build
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
%s
%s
FROM nginx:alpine
COPY --from=build /app/out /usr/share/nginx/html
COPY %s /etc/nginx/conf.d/default.conf
`, nodeInstall, nodeBuild, frameworkNginxConfName)
		return writeFramework(repoDir, df, 80)

	case "standalone":
		df := fmt.Sprintf(`# Auto-generated by VAC (framework: nextjs, mode: standalone).
# Do not edit — regenerated on every deploy.
FROM node:22-alpine AS build
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
%s
%s
RUN mkdir -p public .next/standalone .next/static
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=build /app/public ./public
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
EXPOSE 3000
CMD ["node", "server.js"]
`, nodeInstall, nodeBuild)
		return writeFramework(repoDir, df, 3000)

	default:
		df := fmt.Sprintf(`# Auto-generated by VAC (framework: nextjs).
# Do not edit — regenerated on every deploy.
FROM node:22-alpine AS build
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
%s
%s
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
EXPOSE 3000
CMD ["npx", "next", "start", "-H", "0.0.0.0", "-p", "3000"]
`, nodeInstall, nodeBuild)
		return writeFramework(repoDir, df, 3000)
	}
}

// prepareAstro builds an Astro site. With the @astrojs/node standalone adapter
// it runs the generated server entrypoint (port 4321); otherwise the build is
// static (MPA) and served via nginx.
func prepareAstro(repoDir string, cfg BuildConfig) (string, error) {
	if !detectAstroSSR(repoDir) {
		return prepareStaticNode(repoDir, cfg, FrameworkAstro, "dist", mpaNginxConf())
	}
	df := fmt.Sprintf(`# Auto-generated by VAC (framework: astro, mode: ssr).
# Do not edit — regenerated on every deploy.
FROM node:22-alpine AS build
WORKDIR /app
COPY . .
%s
%s
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=4321
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json
EXPOSE 4321
CMD ["node", "./dist/server/entry.mjs"]
`, nodeInstall, nodeBuild)
	return writeFramework(repoDir, df, 4321)
}

// prepareNode runs a framework-less Node service. The start command is the
// configured one, else resolved from package.json (start script → main →
// conventional entry file). dumb-init is PID 1 so SIGTERM reaches the process.
func prepareNode(repoDir string, cfg BuildConfig) (string, error) {
	port := cfg.Port
	if port == 0 {
		port = 3000
	}
	cmd := nodeStartCmd(repoDir, cfg)
	buildStep := ""
	if pkg, ok := readPackageJSON(repoDir); ok {
		if _, has := pkg.Scripts["build"]; has {
			buildStep = "\n" + nodeBuild
		}
	}
	df := fmt.Sprintf(`# Auto-generated by VAC (framework: node).
# Do not edit — regenerated on every deploy.
FROM node:22-alpine AS build
WORKDIR /app
COPY . .
%s%s
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=%d
RUN apk add --no-cache dumb-init
COPY --from=build /app ./
EXPOSE %d
USER node
CMD %s
`, nodeInstall, buildStep, port, port, cmd)
	return writeFramework(repoDir, df, port)
}

// nodeStartCmd returns a JSON-array CMD (always wrapped in dumb-init). Priority:
// an explicit configured command, then a `start` script, then `node <main>`,
// then a conventional entry file. Falls back to `node server.js`.
func nodeStartCmd(repoDir string, cfg BuildConfig) string {
	if c := strings.TrimSpace(cfg.StartCommand); c != "" {
		return execCmd(append([]string{"dumb-init"}, strings.Fields(c)...))
	}
	if pkg, ok := readPackageJSON(repoDir); ok {
		if _, has := pkg.Scripts["start"]; has {
			return execCmd([]string{"dumb-init", "npm", "start"})
		}
		if m := strings.TrimSpace(pkg.Main); m != "" {
			return execCmd([]string{"dumb-init", "node", m})
		}
	}
	for _, entry := range []string{"server.js", "index.js", "app.js"} {
		if fileExists(filepath.Join(repoDir, entry)) {
			return execCmd([]string{"dumb-init", "node", entry})
		}
	}
	return execCmd([]string{"dumb-init", "node", "server.js"})
}

// execCmd renders a Docker exec-form CMD line, e.g. ["dumb-init","node","x.js"].
func execCmd(parts []string) string {
	quoted := make([]string, len(parts))
	for i, p := range parts {
		quoted[i] = fmt.Sprintf("%q", p)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func writeNginxConf(repoDir, conf string) error {
	if err := os.WriteFile(filepath.Join(repoDir, frameworkNginxConfName), []byte(conf), 0o644); err != nil {
		return fmt.Errorf("adapter: write nginx conf: %w", err)
	}
	return nil
}

// spaNginxConf serves a single-page app: unknown paths fall back to index.html
// so the client-side router handles them. Hashed assets are excluded from the
// fallback (a missing chunk should 404, not return HTML).
func spaNginxConf() string {
	return `server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location /assets/ {
        try_files $uri =404;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
`
}

// mpaNginxConf serves a multi-page static build (Astro/Next export): every route
// is a real .html file, so unknown paths 404 rather than redirecting to a single
// shell.
func mpaNginxConf() string {
	return `server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files $uri $uri.html $uri/ /404.html =404;
    }
}
`
}

var (
	nextStandaloneRe = regexp.MustCompile(`output\s*:\s*['"]standalone['"]`)
	nextExportRe     = regexp.MustCompile(`output\s*:\s*['"]export['"]`)
	astroServerRe    = regexp.MustCompile(`output\s*:\s*['"]server['"]`)
	astroNodeRe      = regexp.MustCompile(`@astrojs/node`)
)

// detectNextMode reads next.config.* for the `output` setting: "standalone",
// "export", or "" (the default server build run via `next start`). Computed
// configs are rare; an unreadable/ambiguous config falls back to the default.
func detectNextMode(repoDir string) string {
	src := readConfig(repoDir, "next.config", ".js", ".mjs", ".ts", ".cjs")
	switch {
	case nextStandaloneRe.MatchString(src):
		return "standalone"
	case nextExportRe.MatchString(src):
		return "export"
	default:
		return ""
	}
}

// detectAstroSSR reports whether the project uses the Astro Node adapter (the
// signal for an on-demand server build) — either the adapter import in
// astro.config.* or @astrojs/node in package.json. Without it the build is
// static.
func detectAstroSSR(repoDir string) bool {
	if pkg, ok := readPackageJSON(repoDir); ok && pkg.hasDep("@astrojs/node") {
		return true
	}
	src := readConfig(repoDir, "astro.config", ".mjs", ".js", ".ts")
	return astroNodeRe.MatchString(src) || astroServerRe.MatchString(src)
}

// readConfig returns the contents of the first base+ext that exists, or "".
func readConfig(repoDir, base string, exts ...string) string {
	for _, ext := range exts {
		if b, err := os.ReadFile(filepath.Join(repoDir, base+ext)); err == nil { //nolint:gosec // G304: operator's cloned build input
			return string(b)
		}
	}
	return ""
}
