package adapter

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// imageAdapter deploys a prebuilt image (e.g. ghcr.io/me/app:1.4.2) with no
// build step and no git repo. It synthesises a minimal compose.yaml with an
// `image:` and no `build:` context, so the pipeline's existing Build step is a
// no-op and `up` pulls the image. The single service is named `app`; when the
// operator declares a port we `expose:` it so VAC auto-detects the internal
// port and attaches the `{slug}--app` alias to vac-edge (a port-less image is a
// non-HTTP worker — no expose, no route).
type imageAdapter struct{}

func (imageAdapter) Kind() string { return KindImage }

// imageComposeTemplate: %s image ref, %s expose block (may be empty).
const imageComposeTemplate = `# Auto-generated by VAC for a prebuilt image.
# Do not edit — regenerated on every deploy.
services:
  app:
    image: %s
    restart: always
%s    env_file:
      - .env
`

// imageRefRe is a permissive sanity check on an image reference. It is NOT a
// full distribution-spec parser — it rejects whitespace, control characters and
// shell metacharacters so a ref can't smuggle anything into the generated
// compose, while accepting the `[registry[:port]/]repo[:tag][@sha256:…]` shapes
// operators actually paste. The real validator is the pull at deploy time.
var imageRefRe = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9._:/@-]*$`)

func (imageAdapter) Prepare(_ context.Context, repoDir string, cfg BuildConfig) (string, error) {
	ref := strings.TrimSpace(cfg.Image)
	if err := validateImageRef(ref); err != nil {
		return "", err
	}

	var expose string
	if cfg.Port > 0 {
		// vac-edge auto-detect reads the compose `expose:` target when `ps`
		// reports no host-published port (invariant D2). Two-space indent puts it
		// under `app:` in the template above.
		expose = fmt.Sprintf("    expose:\n      - \"%d\"\n", cfg.Port)
	}

	body := fmt.Sprintf(imageComposeTemplate, ref, expose)
	dest := composeWrapPath(repoDir)
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("adapter: write compose: %w", err)
	}
	return dest, nil
}

// validateImageRef enforces the same rules as Validate's KindImage case, reused
// at Prepare time so a malformed ref never reaches the generated compose.
func validateImageRef(ref string) error {
	if ref == "" {
		return fmt.Errorf("adapter: image build requires an image reference")
	}
	if !imageRefRe.MatchString(ref) {
		return fmt.Errorf("adapter: invalid image reference %q", ref)
	}
	return nil
}
