package adapter

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// staticAdapter serves a directory of pre-built files through a tiny nginx
// container on vac-edge. The files are **baked into an image** (a generated
// Dockerfile that COPYs them in), not bind-mounted from the repo: vac-api drives
// the host daemon over a mounted socket while its repo tree lives in the
// `vac_repos` named volume, so a host bind mount would resolve the source
// against the daemon's filesystem — where the cloned files don't exist — and
// silently serve an empty site (the daemon even auto-creates the missing mount
// source as an empty dir). A build context is streamed to the daemon by the
// client, so COPY works regardless of where the volume actually lives.
//
// A file-server container (rather than special-casing the proxy) keeps the
// DNS-alias routing invariant intact: the service exposes port 80, VAC
// auto-detects its internal port, and Caddy routes to it like any app.
type staticAdapter struct{}

func (staticAdapter) Kind() string { return KindStatic }

// staticDockerfileTemplate bakes the static dir into nginx. %s is the COPY
// source (the static dir), then the nginx-conf name twice (scrub + final COPY).
//
// The first stage is a throwaway: when the static root is the repo root, its
// context carries VCS history and the VAC-injected files (including .env, which
// may hold decrypted secrets). Scrubbing them there means they never reach the
// served image — so they can't be fetched over HTTP — without leaving them in a
// lower image layer the way a single-stage `RUN rm` would.
const staticDockerfileTemplate = `# Auto-generated by VAC (static site).
# Do not edit — regenerated on every deploy.
FROM nginx:alpine AS site
WORKDIR /site
COPY %s ./
RUN rm -rf .git .env .dockerignore Dockerfile.vac compose.yaml %s

FROM nginx:alpine
COPY --from=site /site /usr/share/nginx/html
COPY %s /etc/nginx/conf.d/default.conf
`

const staticNginxConfName = "vac-static.conf"

func (staticAdapter) Prepare(_ context.Context, repoDir string, cfg BuildConfig) (string, error) {
	dir := strings.TrimSpace(cfg.StaticDir)
	if dir == "" {
		dir = "."
	}
	// The dir is interpolated into a shell-form Dockerfile `COPY` line, so reject
	// whitespace (which would split it into extra args), quotes, and the path
	// separators a value could use to break the instruction. safeRepoPath already
	// blocks traversal/absolute paths.
	if strings.ContainsAny(dir, ":\"'\\\n\r\t ") {
		return "", fmt.Errorf("adapter: static directory %q contains unsupported characters", dir)
	}
	full, err := safeRepoPath(repoDir, dir)
	if err != nil {
		return "", err
	}
	if !dirExists(full) {
		return "", fmt.Errorf("adapter: static directory %q not found in repo", dir)
	}

	confPath := filepath.Join(repoDir, staticNginxConfName)
	if err := os.WriteFile(confPath, []byte(staticNginxConf(cfg.SPAFallback)), 0o644); err != nil {
		return "", fmt.Errorf("adapter: write nginx conf: %w", err)
	}

	df := fmt.Sprintf(staticDockerfileTemplate, filepath.ToSlash(dir), staticNginxConfName, staticNginxConfName)
	return writeFramework(repoDir, df, 80)
}

// staticNginxConf returns the server block. With spaFallback, unknown paths
// fall back to index.html (client-side routing); otherwise they 404.
func staticNginxConf(spaFallback bool) string {
	fallback := "=404"
	if spaFallback {
		fallback = "/index.html"
	}
	return fmt.Sprintf(`server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    location / {
        try_files $uri $uri/ %s;
    }
}
`, fallback)
}
