package adapter

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// staticAdapter serves a built output directory through a tiny nginx container
// on vac-edge. A file-server container (rather than special-casing the proxy)
// keeps the DNS-alias routing invariant intact: the service publishes port 80,
// VAC auto-detects its internal port, and Caddy routes to it like any app.
type staticAdapter struct{}

func (staticAdapter) Kind() string { return KindStatic }

// staticComposeTemplate: %q staticDir mount, %q nginx conf mount.
const staticComposeTemplate = `# Auto-generated by VAC for a static site.
# Do not edit — regenerated on every deploy.
services:
  app:
    image: nginx:alpine
    restart: always
    ports:
      - "80"
    volumes:
      - "%s:/usr/share/nginx/html:ro"
      - "%s:/etc/nginx/conf.d/default.conf:ro"
`

const staticNginxConfName = "vac-static.conf"

func (staticAdapter) Prepare(_ context.Context, repoDir string, cfg BuildConfig) (string, error) {
	dir := strings.TrimSpace(cfg.StaticDir)
	if dir == "" {
		dir = "."
	}
	// The dir is interpolated into a quoted compose volume line; reject the
	// characters that could break out of the quoted scalar or inject extra
	// volume fields (`:` separates source/target/opts; quotes/newlines escape
	// the YAML string). safeRepoPath already blocks traversal/absolute paths.
	if strings.ContainsAny(dir, ":\"'\n\r\t") {
		return "", fmt.Errorf("adapter: static directory %q contains unsupported characters", dir)
	}
	full, err := safeRepoPath(repoDir, dir)
	if err != nil {
		return "", err
	}
	if !dirExists(full) {
		return "", fmt.Errorf("adapter: static directory %q not found in repo", dir)
	}

	confPath := filepath.Join(repoDir, staticNginxConfName)
	if err := os.WriteFile(confPath, []byte(staticNginxConf(cfg.SPAFallback)), 0o644); err != nil {
		return "", fmt.Errorf("adapter: write nginx conf: %w", err)
	}

	body := fmt.Sprintf(staticComposeTemplate, "./"+filepath.ToSlash(dir), "./"+staticNginxConfName)
	dest := composeWrapPath(repoDir)
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("adapter: write compose: %w", err)
	}
	return dest, nil
}

// staticNginxConf returns the server block. With spaFallback, unknown paths
// fall back to index.html (client-side routing); otherwise they 404.
func staticNginxConf(spaFallback bool) string {
	fallback := "=404"
	if spaFallback {
		fallback = "/index.html"
	}
	return fmt.Sprintf(`server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    location / {
        try_files $uri $uri/ %s;
    }
}
`, fallback)
}
