/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStorageRouteImport } from './routes/_app/storage'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppDeploymentsRouteImport } from './routes/_app/deployments'
import { Route as AppDatabaseRouteImport } from './routes/_app/database'
import { Route as AppBackupsRouteImport } from './routes/_app/backups'
import { Route as AppAddonsRouteImport } from './routes/_app/addons'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppAppsIndexRouteImport } from './routes/_app/apps/index'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsInstanceRouteImport } from './routes/_app/settings/instance'
import { Route as AppSettingsDomainsRouteImport } from './routes/_app/settings/domains'
import { Route as AppSettingsDeploymentsRouteImport } from './routes/_app/settings/deployments'
import { Route as AppSettingsDangerRouteImport } from './routes/_app/settings/danger'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings/appearance'
import { Route as AppSettingsApiTokensRouteImport } from './routes/_app/settings/api-tokens'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppAppsNewRouteImport } from './routes/_app/apps/new'
import { Route as AppAppsAppIdRouteImport } from './routes/_app/apps/$appId'
import { Route as AppAppsAppIdIndexRouteImport } from './routes/_app/apps/$appId/index'
import { Route as AppAppsAppIdSettingsRouteImport } from './routes/_app/apps/$appId/settings'
import { Route as AppAppsAppIdServicesRouteImport } from './routes/_app/apps/$appId/services'
import { Route as AppAppsAppIdPreviewsRouteImport } from './routes/_app/apps/$appId/previews'
import { Route as AppAppsAppIdOverviewRouteImport } from './routes/_app/apps/$appId/overview'
import { Route as AppAppsAppIdLogsRouteImport } from './routes/_app/apps/$appId/logs'
import { Route as AppAppsAppIdEnvironmentRouteImport } from './routes/_app/apps/$appId/environment'
import { Route as AppAppsAppIdDeploysRouteImport } from './routes/_app/apps/$appId/deploys'
import { Route as AppAppsAppIdDatabasesRouteImport } from './routes/_app/apps/$appId/databases'
import { Route as AppAppsAppIdBackupsRouteImport } from './routes/_app/apps/$appId/backups'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStorageRoute = AppStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsRoute = AppDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseRoute = AppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupsRoute = AppBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppRoute,
} as any)
const AppAddonsRoute = AppAddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsInstanceRoute = AppSettingsInstanceRouteImport.update({
  id: '/instance',
  path: '/instance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDomainsRoute = AppSettingsDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDeploymentsRoute = AppSettingsDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDangerRoute = AppSettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiTokensRoute = AppSettingsApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppAppsNewRoute = AppAppsNewRouteImport.update({
  id: '/apps/new',
  path: '/apps/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppIdRoute = AppAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsAppIdIndexRoute = AppAppsAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdSettingsRoute = AppAppsAppIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdServicesRoute = AppAppsAppIdServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdPreviewsRoute = AppAppsAppIdPreviewsRouteImport.update({
  id: '/previews',
  path: '/previews',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdOverviewRoute = AppAppsAppIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdLogsRoute = AppAppsAppIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdEnvironmentRoute = AppAppsAppIdEnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdDeploysRoute = AppAppsAppIdDeploysRouteImport.update({
  id: '/deploys',
  path: '/deploys',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdDatabasesRoute = AppAppsAppIdDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)
const AppAppsAppIdBackupsRoute = AppAppsAppIdBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AppAppsAppIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/activity': typeof AppActivityRoute
  '/addons': typeof AppAddonsRoute
  '/backups': typeof AppBackupsRoute
  '/database': typeof AppDatabaseRoute
  '/deployments': typeof AppDeploymentsRoute
  '/logs': typeof AppLogsRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/storage': typeof AppStorageRoute
  '/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/apps/new': typeof AppAppsNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/api-tokens': typeof AppSettingsApiTokensRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/danger': typeof AppSettingsDangerRoute
  '/settings/deployments': typeof AppSettingsDeploymentsRoute
  '/settings/domains': typeof AppSettingsDomainsRoute
  '/settings/instance': typeof AppSettingsInstanceRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/apps/': typeof AppAppsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/apps/$appId/backups': typeof AppAppsAppIdBackupsRoute
  '/apps/$appId/databases': typeof AppAppsAppIdDatabasesRoute
  '/apps/$appId/deploys': typeof AppAppsAppIdDeploysRoute
  '/apps/$appId/environment': typeof AppAppsAppIdEnvironmentRoute
  '/apps/$appId/logs': typeof AppAppsAppIdLogsRoute
  '/apps/$appId/overview': typeof AppAppsAppIdOverviewRoute
  '/apps/$appId/previews': typeof AppAppsAppIdPreviewsRoute
  '/apps/$appId/services': typeof AppAppsAppIdServicesRoute
  '/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/apps/$appId/': typeof AppAppsAppIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/activity': typeof AppActivityRoute
  '/addons': typeof AppAddonsRoute
  '/backups': typeof AppBackupsRoute
  '/database': typeof AppDatabaseRoute
  '/deployments': typeof AppDeploymentsRoute
  '/logs': typeof AppLogsRoute
  '/security': typeof AppSecurityRoute
  '/storage': typeof AppStorageRoute
  '/apps/new': typeof AppAppsNewRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/api-tokens': typeof AppSettingsApiTokensRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/danger': typeof AppSettingsDangerRoute
  '/settings/deployments': typeof AppSettingsDeploymentsRoute
  '/settings/domains': typeof AppSettingsDomainsRoute
  '/settings/instance': typeof AppSettingsInstanceRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/apps': typeof AppAppsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/apps/$appId/backups': typeof AppAppsAppIdBackupsRoute
  '/apps/$appId/databases': typeof AppAppsAppIdDatabasesRoute
  '/apps/$appId/deploys': typeof AppAppsAppIdDeploysRoute
  '/apps/$appId/environment': typeof AppAppsAppIdEnvironmentRoute
  '/apps/$appId/logs': typeof AppAppsAppIdLogsRoute
  '/apps/$appId/overview': typeof AppAppsAppIdOverviewRoute
  '/apps/$appId/previews': typeof AppAppsAppIdPreviewsRoute
  '/apps/$appId/services': typeof AppAppsAppIdServicesRoute
  '/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/apps/$appId': typeof AppAppsAppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/addons': typeof AppAddonsRoute
  '/_app/backups': typeof AppBackupsRoute
  '/_app/database': typeof AppDatabaseRoute
  '/_app/deployments': typeof AppDeploymentsRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/storage': typeof AppStorageRoute
  '/_app/apps/$appId': typeof AppAppsAppIdRouteWithChildren
  '/_app/apps/new': typeof AppAppsNewRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/api-tokens': typeof AppSettingsApiTokensRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/danger': typeof AppSettingsDangerRoute
  '/_app/settings/deployments': typeof AppSettingsDeploymentsRoute
  '/_app/settings/domains': typeof AppSettingsDomainsRoute
  '/_app/settings/instance': typeof AppSettingsInstanceRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/apps/': typeof AppAppsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/apps/$appId/backups': typeof AppAppsAppIdBackupsRoute
  '/_app/apps/$appId/databases': typeof AppAppsAppIdDatabasesRoute
  '/_app/apps/$appId/deploys': typeof AppAppsAppIdDeploysRoute
  '/_app/apps/$appId/environment': typeof AppAppsAppIdEnvironmentRoute
  '/_app/apps/$appId/logs': typeof AppAppsAppIdLogsRoute
  '/_app/apps/$appId/overview': typeof AppAppsAppIdOverviewRoute
  '/_app/apps/$appId/previews': typeof AppAppsAppIdPreviewsRoute
  '/_app/apps/$appId/services': typeof AppAppsAppIdServicesRoute
  '/_app/apps/$appId/settings': typeof AppAppsAppIdSettingsRoute
  '/_app/apps/$appId/': typeof AppAppsAppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/activity'
    | '/addons'
    | '/backups'
    | '/database'
    | '/deployments'
    | '/logs'
    | '/security'
    | '/settings'
    | '/storage'
    | '/apps/$appId'
    | '/apps/new'
    | '/settings/account'
    | '/settings/api-tokens'
    | '/settings/appearance'
    | '/settings/danger'
    | '/settings/deployments'
    | '/settings/domains'
    | '/settings/instance'
    | '/settings/notifications'
    | '/apps/'
    | '/settings/'
    | '/apps/$appId/backups'
    | '/apps/$appId/databases'
    | '/apps/$appId/deploys'
    | '/apps/$appId/environment'
    | '/apps/$appId/logs'
    | '/apps/$appId/overview'
    | '/apps/$appId/previews'
    | '/apps/$appId/services'
    | '/apps/$appId/settings'
    | '/apps/$appId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/activity'
    | '/addons'
    | '/backups'
    | '/database'
    | '/deployments'
    | '/logs'
    | '/security'
    | '/storage'
    | '/apps/new'
    | '/settings/account'
    | '/settings/api-tokens'
    | '/settings/appearance'
    | '/settings/danger'
    | '/settings/deployments'
    | '/settings/domains'
    | '/settings/instance'
    | '/settings/notifications'
    | '/apps'
    | '/settings'
    | '/apps/$appId/backups'
    | '/apps/$appId/databases'
    | '/apps/$appId/deploys'
    | '/apps/$appId/environment'
    | '/apps/$appId/logs'
    | '/apps/$appId/overview'
    | '/apps/$appId/previews'
    | '/apps/$appId/services'
    | '/apps/$appId/settings'
    | '/apps/$appId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/activity'
    | '/_app/addons'
    | '/_app/backups'
    | '/_app/database'
    | '/_app/deployments'
    | '/_app/logs'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/storage'
    | '/_app/apps/$appId'
    | '/_app/apps/new'
    | '/_app/settings/account'
    | '/_app/settings/api-tokens'
    | '/_app/settings/appearance'
    | '/_app/settings/danger'
    | '/_app/settings/deployments'
    | '/_app/settings/domains'
    | '/_app/settings/instance'
    | '/_app/settings/notifications'
    | '/_app/apps/'
    | '/_app/settings/'
    | '/_app/apps/$appId/backups'
    | '/_app/apps/$appId/databases'
    | '/_app/apps/$appId/deploys'
    | '/_app/apps/$appId/environment'
    | '/_app/apps/$appId/logs'
    | '/_app/apps/$appId/overview'
    | '/_app/apps/$appId/previews'
    | '/_app/apps/$appId/services'
    | '/_app/apps/$appId/settings'
    | '/_app/apps/$appId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/storage': {
      id: '/_app/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AppStorageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments': {
      id: '/_app/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AppDeploymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database': {
      id: '/_app/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AppDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backups': {
      id: '/_app/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AppBackupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/addons': {
      id: '/_app/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AppAddonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/instance': {
      id: '/_app/settings/instance'
      path: '/instance'
      fullPath: '/settings/instance'
      preLoaderRoute: typeof AppSettingsInstanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/domains': {
      id: '/_app/settings/domains'
      path: '/domains'
      fullPath: '/settings/domains'
      preLoaderRoute: typeof AppSettingsDomainsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/deployments': {
      id: '/_app/settings/deployments'
      path: '/deployments'
      fullPath: '/settings/deployments'
      preLoaderRoute: typeof AppSettingsDeploymentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/danger': {
      id: '/_app/settings/danger'
      path: '/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof AppSettingsDangerRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-tokens': {
      id: '/_app/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/settings/api-tokens'
      preLoaderRoute: typeof AppSettingsApiTokensRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/apps/new': {
      id: '/_app/apps/new'
      path: '/apps/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AppAppsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appId': {
      id: '/_app/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppAppsAppIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/$appId/': {
      id: '/_app/apps/$appId/'
      path: '/'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof AppAppsAppIdIndexRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/settings': {
      id: '/_app/apps/$appId/settings'
      path: '/settings'
      fullPath: '/apps/$appId/settings'
      preLoaderRoute: typeof AppAppsAppIdSettingsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/services': {
      id: '/_app/apps/$appId/services'
      path: '/services'
      fullPath: '/apps/$appId/services'
      preLoaderRoute: typeof AppAppsAppIdServicesRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/previews': {
      id: '/_app/apps/$appId/previews'
      path: '/previews'
      fullPath: '/apps/$appId/previews'
      preLoaderRoute: typeof AppAppsAppIdPreviewsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/overview': {
      id: '/_app/apps/$appId/overview'
      path: '/overview'
      fullPath: '/apps/$appId/overview'
      preLoaderRoute: typeof AppAppsAppIdOverviewRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/logs': {
      id: '/_app/apps/$appId/logs'
      path: '/logs'
      fullPath: '/apps/$appId/logs'
      preLoaderRoute: typeof AppAppsAppIdLogsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/environment': {
      id: '/_app/apps/$appId/environment'
      path: '/environment'
      fullPath: '/apps/$appId/environment'
      preLoaderRoute: typeof AppAppsAppIdEnvironmentRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/deploys': {
      id: '/_app/apps/$appId/deploys'
      path: '/deploys'
      fullPath: '/apps/$appId/deploys'
      preLoaderRoute: typeof AppAppsAppIdDeploysRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/databases': {
      id: '/_app/apps/$appId/databases'
      path: '/databases'
      fullPath: '/apps/$appId/databases'
      preLoaderRoute: typeof AppAppsAppIdDatabasesRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
    '/_app/apps/$appId/backups': {
      id: '/_app/apps/$appId/backups'
      path: '/backups'
      fullPath: '/apps/$appId/backups'
      preLoaderRoute: typeof AppAppsAppIdBackupsRouteImport
      parentRoute: typeof AppAppsAppIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsApiTokensRoute: typeof AppSettingsApiTokensRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsDangerRoute: typeof AppSettingsDangerRoute
  AppSettingsDeploymentsRoute: typeof AppSettingsDeploymentsRoute
  AppSettingsDomainsRoute: typeof AppSettingsDomainsRoute
  AppSettingsInstanceRoute: typeof AppSettingsInstanceRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsApiTokensRoute: AppSettingsApiTokensRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsDangerRoute: AppSettingsDangerRoute,
  AppSettingsDeploymentsRoute: AppSettingsDeploymentsRoute,
  AppSettingsDomainsRoute: AppSettingsDomainsRoute,
  AppSettingsInstanceRoute: AppSettingsInstanceRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppAppsAppIdRouteChildren {
  AppAppsAppIdBackupsRoute: typeof AppAppsAppIdBackupsRoute
  AppAppsAppIdDatabasesRoute: typeof AppAppsAppIdDatabasesRoute
  AppAppsAppIdDeploysRoute: typeof AppAppsAppIdDeploysRoute
  AppAppsAppIdEnvironmentRoute: typeof AppAppsAppIdEnvironmentRoute
  AppAppsAppIdLogsRoute: typeof AppAppsAppIdLogsRoute
  AppAppsAppIdOverviewRoute: typeof AppAppsAppIdOverviewRoute
  AppAppsAppIdPreviewsRoute: typeof AppAppsAppIdPreviewsRoute
  AppAppsAppIdServicesRoute: typeof AppAppsAppIdServicesRoute
  AppAppsAppIdSettingsRoute: typeof AppAppsAppIdSettingsRoute
  AppAppsAppIdIndexRoute: typeof AppAppsAppIdIndexRoute
}

const AppAppsAppIdRouteChildren: AppAppsAppIdRouteChildren = {
  AppAppsAppIdBackupsRoute: AppAppsAppIdBackupsRoute,
  AppAppsAppIdDatabasesRoute: AppAppsAppIdDatabasesRoute,
  AppAppsAppIdDeploysRoute: AppAppsAppIdDeploysRoute,
  AppAppsAppIdEnvironmentRoute: AppAppsAppIdEnvironmentRoute,
  AppAppsAppIdLogsRoute: AppAppsAppIdLogsRoute,
  AppAppsAppIdOverviewRoute: AppAppsAppIdOverviewRoute,
  AppAppsAppIdPreviewsRoute: AppAppsAppIdPreviewsRoute,
  AppAppsAppIdServicesRoute: AppAppsAppIdServicesRoute,
  AppAppsAppIdSettingsRoute: AppAppsAppIdSettingsRoute,
  AppAppsAppIdIndexRoute: AppAppsAppIdIndexRoute,
}

const AppAppsAppIdRouteWithChildren = AppAppsAppIdRoute._addFileChildren(
  AppAppsAppIdRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAddonsRoute: typeof AppAddonsRoute
  AppBackupsRoute: typeof AppBackupsRoute
  AppDatabaseRoute: typeof AppDatabaseRoute
  AppDeploymentsRoute: typeof AppDeploymentsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppStorageRoute: typeof AppStorageRoute
  AppAppsAppIdRoute: typeof AppAppsAppIdRouteWithChildren
  AppAppsNewRoute: typeof AppAppsNewRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAddonsRoute: AppAddonsRoute,
  AppBackupsRoute: AppBackupsRoute,
  AppDatabaseRoute: AppDatabaseRoute,
  AppDeploymentsRoute: AppDeploymentsRoute,
  AppLogsRoute: AppLogsRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppStorageRoute: AppStorageRoute,
  AppAppsAppIdRoute: AppAppsAppIdRouteWithChildren,
  AppAppsNewRoute: AppAppsNewRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
